# Generated by Django 3.1.2 on 2020-10-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('api_key', models.CharField(max_length=120)),
                ('check_type', models.CharField(max_length=120)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('order', models.JSONField()),
                ('status', models.CharField(max_length=120)),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.printer')),
            ],
        ),
    ]
