# Generated by Django 3.1.2 on 2020-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20201026_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=120),
        ),
    ]
