# Generated by Django 3.1.2 on 2020-10-26 18:07

import checks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20201026_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(default=checks.models.api_key, max_length=120, unique=True),
        ),
    ]
