# Generated by Django 3.1.2 on 2020-10-28 11:53

import checks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_auto_20201026_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.printer'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(default=checks.models.api_key, max_length=120),
        ),
    ]
