# Generated by Django 3.1.2 on 2020-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_auto_20201028_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(max_length=120),
        ),
    ]
