# Generated by Django 3.1.2 on 2020-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0007_auto_20201028_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=120),
        ),
    ]
